---
- hosts: ws
  become: true
  gather_facts: yes
  vars:
    user_name: Huguette
    group_name: cloud
  vars_files:
    - variables.yml

  tasks:
    - name: create user Huguette
      user:
        name: "{{user_name}}"
        state: present
        comment: Huguette Tchamegot
        shell: /bin/bash
    - name: create group
      group:
        name: "{{group_name}}"
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family=="Debian"
    - name: Install nginx on redhat family
      package:
        name: httpd
        state: present      
      when: ansible_os_family=="RedHat"      
    - name: start nginx daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
    - name: create group
      group:
        name: cloudteam
        state: present

    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: create directory
      file:
        path: /tmp/os
        state: directory

    - name: Copy content to index
      copy:
        dest: /var/www/html/index.html
        content: '<h1> This is created using ansible </h1>'
      